### ISSUE TITLE
Can i run this package on cpu?

### ISSUE THREAD

**Issue by adillacad11** [BAN2ARU/yolov8-ros2#2]
I am new in vision and ros. please helpp :)

i try this package on cpu because my device is raspberry pi 4 with cpu

as in the code there is an option cpu/gpu to use. but when i go to edit cuda:0 to CPU. is getting error or the node isn't show up in rqt_graph. please help, thanks!

**Comment by BAN2ARU** [comment]
Hello, @adillacad11  :)

When I executed the following command with the RealSense camera, it worked fine:
`ros2 launch yolov8_launch yolov8_foxy.launch.py img_topic:=/camera/color/image_raw device:=cpu`

You should change **img_topic** to the image topic from the camera you are using.

Instead of using **rqt_graph**, have you considered checking it in **rviz2**? After running the command, you can view the YOLO model's result image in rviz2 ( **Add > By topic > /yolov8_result > Image**).

**Comment by adillacad11** [comment]
OHMAYYYGOD THANKYOU :D
you save my life. I already can run it. hehe, thank you so much <3
